# Generated by Django 4.1.5 on 2023-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_card',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
