# Generated by Django 4.1.5 on 2023-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_payment_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
