# Generated by Django 4.1.5 on 2023-02-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_baduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadUser',
        ),
    ]
